INSERT INTO public.silly_words(
	id, name, definition)
	VALUES 
    (1, 'Bumfuzzle', 'Confused or perplexed'),
    (2, 'Fartlek', 'When runners change between sprinting and jogging'),
	(3,'Everywhen','Meaning always, or all the time'),
	(4,'Erf','A plot of land'),
	(5,'Hullaballoo','A commotion or a fuss'),
	(6,'Meldrop','A drop of mucus that hangs from your nose'),
	(7,'Obelus','The division symbol in a math problem'),
	(8,'Sozzled','Intoxicated'),
	(9,'Bumbershoot','Umbrella'),
	(10,'Titter','Laugh or giggle'),
	(11,'Smicker','To look amorously after someone'),
	(12,'Cleek','Big hook'),
	(13, 'Whippersnapper', 'A young, overconfident person'),
	(14,'Salopettes','A pair of high-waisted skiing pants with shoulder straps'),
	(15,'Biblioklept','A person who steals books'),
	(16,'Accubation','A person who eats or drinks while lying down'),
	(17,'Lollygag','A person who is doing something that is not useful'),
	(18,'Abecedarian','Anyone who is currently learning the alphabet'),
	(19,'Bamboozled','Tricked'),
	(20,'Cutesy-poo','Sickeningly cute'),
	(21,'Flabbergast','Shocked'),
	(22,'Foppish','Excessively concerned about your clothes or appearance'),
	(23,'Cattywampus','Going poorly, awkwardly, or in the wrong direction'),
	(24,'Noob','Inexperienced, typically using the internet or a video game'),
	(25,'Octothorpe','The real name of the hashtag symbol'),
	(26,'Schmooze','Talking to someone to impress them in a firednly or lively way'),
	(27,'Finifugal','Afraid of finishing anything'),
	(28,'Smaze','A combination of smoke and haze'),
	(29,'Skirl','The sound a bagpipe makes'),
	(30,'Adorbs','A shortened form of the word adorable'),
	(31,'Waesucks','An alternative to the word alas'),
	(32,'Widdershins','Moving in the wrong direction or counter-clockwise'),
	(33,'Blubber','A thick layer of fat'),
	(34,'Dollop','A quantity of something, usually food'),
	(35,'Festooned','How a place is decorated'),
	(36,'Fuddy-duddy','Very old-fashioned'),
	(37,'Gobbledygook','Gibberish'),
	(38,'Popple','Choppy seas'),
	(39,'Hodgepodge','A mix of various random items'),
	(40,'Ramshackle','Something that looks like it is close to falling apart'),
	(41,'Wishy-washy','Someone who struggles to make decisions'),
	(42,'Flummoxed','Utterly confused'),
	(43,'Gardyloo','A warning cry"'),
	(44,'Collywobbles','A stomach ache'),
	(45,'Billingsgate','Foul-mouthed or abusive language'),
	(46,'Lickety-split','As soon as possible'),
	(47,'Slumgullion','A cheap meat stew'),
	(48,'Ill-willie','Having an unfriednly disposition'),
	(49,'Conjubilant','Shouting together with joy'),
	(50,'Futz','Wasting your time');